#!/usr/bin/bash

# little script to run puzzle solutions with input from stdin
# ./run 01

set -e

stack ghc \
    --package groups \
    --package lens \
    --package megaparsec \
    --package pcre-heavy \
    --package split \
    -- -O2 -threaded Day$1.hs

printf "Running Day$1 ...\n\n"
time ./Day$1 +RTS -N <input/day$1.in

rm Day$1 Day$1.hi Day$1.o Day$1.dyn_hi Day$1.dyn_o 2>/dev/null
