#!/usr/bin/bash

# little script to run puzzle solutions with input from stdin 
# ./run day1

stack runghc \
    --package split \
    --package regex-tdfa \
    --package lens \
    -- $1.hs \
    <input/$1.in
