#!/usr/bin/bash

# little script to run puzzle solutions with input from stdin
# ./run day1

set -e

stack ghc \
    --package lens \
    --package megaparsec \
    --package pcre-heavy \
    --package split \
    -- -O2 -threaded $1.hs

printf "Running $1 ...\n\n"
time ./$1 +RTS -N <input/$1.in

rm $1 $1.hi $1.o $1.dyn_hi $1.dyn_o 2>/dev/null
